name: Build_and_Deploy_Cloud_Web_App_to_AWS_ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: fraud-detection-repo
  AWS_DEFAULT_REGION: "ca-central-1"
  IMAGE_REPO_NAME: fraud-detection-repo
  AWS_ACCOUNT_ID: 108271871935
  IMAGE_TAG: latest
  CLUSTER_NAME: WebServerCluster
  SERVICE_NAME: WebServerService

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Linting Python
      - name: Lint Python code
        run: |
          pip install flake8
          flake8 .
          
      # Linting Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1
        with:
          dockerfile: Dockerfile
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Log in to Amazon ECR
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          echo "AWS ECR Login successful at $(date)"

      - name: Build the Docker image
        run: |
          echo "Build started on $(date)"
          docker build -t $IMAGE_REPO_NAME .
          
      # --- CONTAINER SECURITY SCANNING ---
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          severity: HIGH,CRITICAL
          exit-code: '1'          # Fail pipeline if vulnerabilities found
          ignore-unfixed: true    # Ignore vulnerabilities with no upstream fix
          
      # -------Container image tagging ------------------------------
      - name: Tag Docker image
        run: |
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          echo "Pushing image..."
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          echo "Image pushed successfully at $(date)"
          
      - name: Deploy to AWS ECS
        run: |
          echo "Deploying to ECS cluster $CLUSTER_NAME..."
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
          echo "Deployment to ECS cluster triggered at $(date)"
